# Setup
title:            'State of Connecticut'
tagline:          'Data Sharing Playbook'
description:      'Connecticut Data Playbook'

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-default-layout
  
author:
  name:           'State of Connecticut'
  url:            https://github.com/CTOpenData/data-sharing-playbook

# Custom vars
version:          1.2.0

github:
  repo:           https://github.com/CTOpenData/data-sharing-playbook

# Google Analytics
google_analytics: UA-56144207-2
